### PR TITLE
Bugfix check api availability

### LINKED ISSUE #160: When improperly configured, the tool still attempts to access Shopify
This results in gross error messages that don't give any insight into what is wrong. It's confusing and not user friendly

### PR DESCRIPTION
**Pull request by csaunders**
In order to make the tool more user friendly this causes pre-emptive API checks to ensure that the API is accessible and the configuration is setup correctly.

When the configuration is not valid, the user will be presented with a screen that helps them debug what could be going wrong. This relies on their `store` being correct, but if it isn't should look wrong and might help them debug it more easily.

screenshot 2015-09-01 10 54 05

**Note:** I've bumped the version because I plan on releasing a new gem since this will help reduce duplicate bug reports.

Fixes #160 #146

Please review @nickhoffman @ilikeorangutans 

/cc @stevebosworth @cshold @mpiotrowicz

### CODE REVIEW

File: lib/shopify_theme/api_checker.rb [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+    def initialize(client)
+      @client = client
+    end
+
+    def test_connectivity
+      return APIResult.new(client.get_index)
+    end
+
+    private
+    attr_reader :client
```
Comment (nickhoffman) [inline lib/shopify_theme/api_checker.rb]: `attr_reader` is usually placed near the top of classes. It doesn't need to be after `private` .

File: lib/shopify_theme/api_checker.rb [hunk 2]
```diff
@@ -0,0 +1,39 @@
+module ShopifyTheme
+  class APIChecker
+    class APIResult
+      def initialize(http_response)
+        @response = http_response
+      end
+
+      def accessed_api?
+        response.code == 200
```
Comment (nickhoffman) [inline lib/shopify_theme/api_checker.rb]: I'd throw all of these HTTP status codes into aptly-named constants.

File: lib/shopify_theme/api_checker.rb [hunk 3]
```diff
@@ -0,0 +1,39 @@
+module ShopifyTheme
+  class APIChecker
+    class APIResult
```
Comment (nickhoffman) [inline lib/shopify_theme/api_checker.rb]: Any reason not to put this class in its own file?

File: lib/shopify_theme/cli.rb [hunk 4]
```diff
@@ -36,18 +36,28 @@ class Cli < Thor
     end
 
     desc "check", "check configuration"
-    def check
-      if ShopifyTheme.check_config
-        say("Configuration [OK]", :green)
+    def check(exit_on_failure=false)
+      result = APIChecker.new(ShopifyTheme).test_connectivity
+      if result.api_down?
```
Comment (nickhoffman) [inline lib/shopify_theme/cli.rb]: :cop: could you add a blank line above this, please?

File: lib/shopify_theme/cli.rb [hunk 5]
```diff
@@ -36,18 +36,28 @@ class Cli < Thor
...
+        say("Cannot connect to Shopify. API appears to be down", :red)
+        say("Visit http://status.shopify.com for more details", :yello)
+      elsif result.invalid_config?
+        say("Cannot connect to Shopify. Configuration is invalid.", :red)
+        say("Verify that your API Key, Password and Domain are correct.", :yellow)
```
Comment (nickhoffman) [inline lib/shopify_theme/cli.rb]: Nitpick: The words "Key", "Password", and "Domain" should be lowercase.

File: lib/shopify_theme/cli.rb [hunk 6]
```diff
@@ -36,18 +36,28 @@ class Cli < Thor
...
+        say("Visit https://github.com/shopify/shopify_theme#configuration for more details", :yellow)
+        say("If your shop domain is correct, the following URL should take you to the Private Apps page for the shop:", :yellow)
+        say("  https://#{config[:store]}/admin/apps/private", :yellow)
       else
-        say("Configuration [FAIL]", :red)
+        say("Shopify API is accessible and Configuration is valid", :green) unless exit_on_failure
```
Comment (nickhoffman) [inline lib/shopify_theme/cli.rb]: Nitpick: "Configuration" should be lowercase

File: lib/shopify_theme/cli.rb [hunk 7]
```diff
@@ -36,18 +36,28 @@ class Cli < Thor
...
       end
+      exit(1) if result.cannot_access_api? && exit_on_failure
```
Comment (nickhoffman) [inline lib/shopify_theme/cli.rb]: :cop: could you add a blank line above this, please?

File: lib/shopify_theme/cli.rb [hunk 8]
```diff
@@ -36,18 +36,28 @@ class Cli < Thor
...
     end
 
     desc "configure API_KEY PASSWORD STORE THEME_ID", "generate a config file for the store to connect to"
     def configure(api_key=nil, password=nil, store=nil, theme_id=nil)
       config = {:api_key => api_key, :password => password, :store => store, :theme_id => theme_id}
       create_file('config.yml', config.to_yaml)
+      check(true)
```
Comment (nickhoffman) [inline lib/shopify_theme/cli.rb]: If the check fails, do we want to leave the config file in place with invalid values?

File: spec/unit/api_checker_spec.rb [hunk 9]
```diff
@@ -0,0 +1,50 @@
+require 'spec_helper'
+require 'shopify_theme'
+require 'shopify_theme/api_checker'
+
+module ShopifyTheme
+  describe "APIChecker" do
+    include WebMock::API
+    attr_reader :checker
```
Comment (nickhoffman) [inline spec/unit/api_checker_spec.rb]: :police_car: Could you add a blank line before and after this line, please? Whitespace FTW.

File: spec/unit/api_checker_spec.rb [hunk 10]
```diff
@@ -0,0 +1,50 @@
...
+      VCR.use_cassette("api_check_unauthorized") do
+        stub_request(:get, request_root).to_return(body: "DENIED", status: 401)
+        response = checker.test_connectivity
+        assert response.invalid_config?
+      end
+    end
+
+    def request_root
+      "https://abracadabra:alakazam@something.myshopify.com"
+    end
```
Comment (nickhoffman) [inline spec/unit/api_checker_spec.rb]: The API key and password should be interpolated from `ShopifyTheme.config` .

Also, any particular reason to make this a method rather than an ivar?

File: lib/shopify_theme/api_checker.rb (hunk 3 above)
Comment (csaunders) [inline lib/shopify_theme/api_checker.rb]: I don't really see the point of it at the moment. So I figured I could just let it live in here.

If it starts to get more complicated then I'll probably move it out.

File: lib/shopify_theme/api_checker.rb (hunk 1 above)
Comment (csaunders) [inline lib/shopify_theme/api_checker.rb]: It's mostly just so I can make the method call instead of saying `@ivar` in my classes.

File: lib/shopify_theme/cli.rb (hunk 8 above)
Comment (csaunders) [inline lib/shopify_theme/cli.rb]: I'm not sure what to do with that. I'd prefer to leave it there so user can look at it and at least show what was generated in a bug report.

File: lib/shopify_theme/api_checker.rb (hunk 1 above)
Comment (nickhoffman) [inline lib/shopify_theme/api_checker.rb]: Yup. But `attr_reader` is usually placed near the top of the class, and doesn't need to be located after `private` . I'd move it up.

File: lib/shopify_theme/cli.rb (hunk 8 above)
Comment (nickhoffman) [inline lib/shopify_theme/cli.rb]: :+1:
